[context.library]
  command = "npm run build-storybook"
  publish = "/storybook-static"

[context.consumer]
  command = "npm run build"
  publish = "/dist"

[context.temp]
  command = "npm run build-storybook"
  publish = "/storybook-static"
